### Imports and Settings

In [1]:
import os
import json
from datetime import datetime

import numpy as np
import pandas as pd

import torch as torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

# utils
from data.dataset_modul import Dataset
from models.fst_model import Model
from utils.preprocessing import preprocessing
from utils.utils import train_model, combined_metrics, plot_tsne_embeddings

# seed settings
seed = 42

In [2]:
# cuda settings

if torch.cuda.is_available():
    device_id = torch.cuda.current_device()
    device = torch.device('cuda:%d' % device_id)
    print(torch.cuda.get_device_name(device_id))
else:
    device = torch.device('cpu')

NVIDIA GeForce RTX 4060 Ti

# 1. Load Dataset

In [3]:
# datset paths
sider_path = "data/datasets/sider.csv"
tox_path = "data/datasets/toxcast_data.csv"

In [4]:
dataset = pd.read_csv(sider_path)

nMeas = len([v for v in dataset.iloc[:, 1:].values.flatten() if str(v) != 'nan']) 
nNone =  dataset.isna().sum().sum()

print(f'nMols: {dataset.shape[0]}\nnTasks: {dataset.shape[1]}\nnNone: {nNone}\nnMeasurments: {nMeas}')

#dataset.head()

nMols: 1427
nTasks: 28
nNone: 0
nMeasurments: 38529

In [5]:
# create triplet-df

triplets = [(i,j,row.iloc[j]) for i,row in dataset.iterrows() for j in range(1,len(row))]
triplet_df = pd.DataFrame(triplets, columns=['mol_id', 'target_id', 'label']) 

#triplet_df.head()

# 2. Preprocessing

### 2.1 Datasplit & Preprocessing

In [6]:
data, dataset, train_triplet, val_triplet, test_triplet = preprocessing(dataset, triplet_df, seed)

Preprocessing done!

In [7]:
# dataset information after preprocessing
nMeas = len([v for v in dataset.iloc[:, 1:].values.flatten() if str(v) != 'nan']) 
nNone =  dataset.isna().sum().sum()
print(f'nMols: {dataset.shape[0]}\nnTasks: {dataset.shape[1]}\nnNone: {nNone}\nnMeasurments: {nMeas}')
dataset.head()

nMols: 1427
nTasks: 28
nNone: 0
nMeasurments: 38529

,smiles,Hepatobiliary disorders,Metabolism and nutrition disorders,Product issues,Eye disorders,Investigations,Musculoskeletal and connective tissue disorders,Gastrointestinal disorders,Social circumstances,Immune system disorders,...,"Congenital, familial and genetic disorders",Infections and infestations,"Respiratory, thoracic and mediastinal disorders",Psychiatric disorders,Renal and urinary disorders,"Pregnancy, puerperium and perinatal conditions",Ear and labyrinth disorders,Cardiac disorders,Nervous system disorders,"Injury, poisoning and procedural complications"
0,C(CNCCNCCNCCN)N,1,1,0,0,1,1,1,0,0,...,0,0,1,1,0,0,1,1,1,0
1,CC(C)(C)C1=CC(=C(C=C1NC(=O)C2=CNC3=CC=CC=C3C2=...,0,1,0,0,1,1,1,0,0,...,0,1,1,0,0,0,1,0,1,0
2,CC[C@]12CC(=C)[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O...,0,1,0,1,1,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
3,CCC12CC(=C)C3C(C1CC[C@]2(C#C)O)CCC4=CC(=O)CCC34,1,1,0,1,1,1,1,0,1,...,1,1,1,1,1,1,0,0,1,1
4,C1C(C2=CC=CC=C2N(C3=CC=CC=C31)C(=O)N)O,1,1,0,1,1,1,1,0,1,...,0,1,1,1,0,0,1,0,1,0

### 2.2 Tests Preprocessing

### 2.3 Defines Sets

In [8]:
train_set = Dataset(data, dataset, train_triplet, supp=8, seed=seed)
val_set   = Dataset(data, dataset, val_triplet, supp=8, train = False, seed=seed)
test_set  = Dataset(data, dataset, test_triplet, supp=8, train = False, seed=seed)

# 3. Model Setup

### 3.1 Tests

### 3.2 Initialiaze Model

In [9]:
# read model config

with open('configs/fst_config.json') as json_file:
    model_config = json.load(json_file)

In [10]:
model_params = {k: v for k, v in model_config.items() if k not in ['opt_lr', 'weight_decay']}
#model_params["encodeLabels"] = False 

model = Model(**model_params) 

criterion = nn.BCELoss()

#criterion = torch.nn.BCEWithLogitsLoss() #uses raw logits

optimizer = optim.AdamW(model.parameters(), lr=model_config["opt_lr"], weight_decay=model_config["weight_decay"])

model.to(device)

Model(
  (encoder): Sequential(
    (0): Linear(in_features=2248, out_features=1124, bias=True)
    (1): SELU()
    (2): AlphaDropout(p=0.1, inplace=False)
    (3): Linear(in_features=1124, out_features=1124, bias=True)
    (4): SELU()
    (5): AlphaDropout(p=0.1, inplace=False)
    (6): Linear(in_features=1124, out_features=1124, bias=True)
  )
  (ln): LayerNorm((1124,), eps=1e-05, elementwise_affine=False)
  (label_encoder): Embedding(3, 1124)
  (transformer_encoder): TransformerEncoder(
    (layers): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=1124, out_features=1124, bias=True)
        )
        (linear1): Linear(in_features=1124, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2048, out_features=1124, bias=True)
        (norm1): LayerNorm((1124,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((1124,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (mlp): Sequential(
    (0): Linear(in_features=1124, out_features=2248, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2248, out_features=1, bias=True)
  )
)

### 3.3 Initalize Dataloaders

In [11]:
BATCH_SIZE = model_config["batch_size"] # 16,32,64
#BATCH_SIZE = 512 # toxcast

train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_set , batch_size=BATCH_SIZE, shuffle=True)

# 4. Training

### 4.1 Tests

### 4.2 Train process

In [28]:
# setup savepath for tensorboardlogs
parent_dir = "runs/notebook/"

if not os.path.exists(parent_dir):
    os.makedirs(parent_dir)

# initialize writer
log_dir = os.path.join(parent_dir, f"{datetime.now().strftime('%d-%m-%Y_%Hh-%Mm')}_{seed=}")
writer = SummaryWriter(log_dir=log_dir)

# setup savepath for model
model_parent = "trainedModels/notebook/"

if not os.path.exists(model_parent):
    os.makedirs(model_parent)
    
save_path =  os.path.join(model_parent, f"model_{seed=}.mdl")

In [29]:
train_config = {
    "model": model,
    "criterion": criterion,
    "optimizer": optimizer,
    "max_epochs": 50,
    "patience": 4,
    "log_interval": 100,
    "val_interval": 4, # set higher to fasten up the process of training
    "save_path": save_path
}

In [30]:
train_model(train_config, writer, train_loader, val_loader, device, BATCH_SIZE)

epoch:6/50 batches:0700/713 avg-train_loss:0.4098, avg-val_loss:0.5595, val-auc:0.7964, val-dauc_pr:0.1970
Finished training...

# 5. Evaluation

In [14]:
model.load_state_dict(torch.load(train_config["save_path"]))

### 5.1 Tests

In [31]:
debug = False

In [16]:
#def auc_score(model, loader, device):
#    """
#    Return mean auc of a given model and dataloader, evaluated per task.
#    """

if debug:
    
    import sys
    import numpy as np
    import pandas as pd
    import seaborn as sns
    import matplotlib.pyplot as plt
    from collections import defaultdict
    
    import torch as torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    
    from sklearn.manifold import TSNE
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import roc_auc_score, average_precision_score,accuracy_score, f1_score
    
    loader = val_loader
    
    model.train(False)
    task_predictions = defaultdict(list)
    task_targets = defaultdict(list)
    
    for batch, data_ in enumerate(loader):
        # compute output
        q, p, n, t = data_["query_mol"].to(device), data_["p_supp"].to(device), data_["n_supp"].to(device),data_["task_id"].to(device)
        predictions = model(q, p, n, train=False)
    
        # Append predictions and targets to the corresponding task lists
        for task_id, pred, target in zip(t.cpu().numpy(), predictions.detach().cpu().numpy(), data_['query_label'].cpu().numpy()):
            task_predictions[task_id].append(pred)
            task_targets[task_id].append(target)
    
    # Calculate auc for each task
    task_aucs = []
    for task_id in task_predictions:
        preds = task_predictions[task_id] 
        targets = task_targets[task_id]
    
        # auc score
        auc = roc_auc_score(targets, preds)
        task_aucs.append(auc)
    
    # Return the mean dAUC PR across all tasks
    mean_auc_pr = np.mean(task_aucs)
    print(f"{mean_auc_pr=}\n")

    for key in task_predictions.keys():
        print(f"{key}:[{set(task_predictions[key])}]\n")

### 5.2 Val-Set Evaluation

In [18]:
combined_metrics(model,val_loader,device)

   Accuracy  F1 Score     AUC  D-AUC PR
0    0.7215    0.7644  0.8004    0.1948

### 5.3 Test-Set Evaluation

In [19]:
combined_metrics(model,test_loader,device)

   Accuracy  F1 Score     AUC  D-AUC PR
0    0.7392    0.7078  0.8127    0.1835

### 5.4 Evalutation after averaging over 10 seeds

In [20]:
# results_path = ...

#avgResults = pd.read_csv("results/avg_results.csv").rename(columns={'Unnamed: 0': 'Model'})
#avgResults

### 5.5 Results without Transformerencoder

In [21]:
#oldResults = pd.read_csv("results/old_avg_results.csv").rename(columns={'Unnamed: 0': 'Model'})
#oldResults

### 5.6 Results without Labelencoding

In [22]:
# results without label encoding
results = pd.read_csv("results/avg_results_wOLabelEncoding.csv").rename(columns={'Unnamed: 0': 'Model'})
results

     Model  Accuracy  F1 Score      AUC  D-AUC PR
0   fs-val   0.74606   0.72134  0.82351   0.20835
1  fs-test   0.73686   0.69017  0.81371   0.19781
2       rf   0.55301   0.53380  0.55107   0.01654

### 5.7 TSNE bevore and after Training

In [23]:
#cardiacIdxs = train_triplet[ train_triplet['target_id'] == 25].index
#len(cardiacIdxs)

In [24]:
#queryMols = [train_set[i]["query_mol"] for i in range(len(cardiacIdxs))]
#len(queryMols)

In [25]:
#train_loader = DataLoader(train_set, batch_size=1427, shuffle=True)

#len(train_loader)

In [26]:
#embeds = []
#for batch, data_ in enumerate(train_loader):
#    # reset gradients
#    with torch.no_grad():
    
        # compute output
#        query, p_supp, n_supp, t = data_["query_mol"].to(device),data_["p_supp"].to(device),data_["n_supp"].to(device),data_["task_id"].to(device)

        # Step 1: Encode query, negative and positive supportset: 
#        p = model.ln(model.encoder(p_supp))
#        n = model.ln(model.encoder(n_supp))
#        q = model.ln(model.encoder(query))

        # get params for label encoding
#        device = p.device
#        n_supps = p.shape[1]
#        currentBatchSize = p.shape[0]

        # Step2: Encode labels of query,as well as negative and positive supportset
#        pl = model.label_encoder( torch.ones(currentBatchSize, n_supps, dtype=torch.long).to(device) )
#        nl = model.label_encoder (torch.zeros(currentBatchSize, n_supps, dtype=torch.long).to(device) )
#        ql = model.label_encoder( torch.ones(currentBatchSize, dtype=torch.long).to(device) *2 )

        # Step 3: Concatenate input embeddings with label embeddings
#        p = torch.cat((p, pl), dim=-1)
#        n = torch.cat((n, nl), dim=-1)
#        q = torch.cat((q, ql), dim=-1)

        # Step 4: Concatenate query with support
#        q = q.unsqueeze(1)  # Add sequence dimension, Shape: (batch_size, 1, 2*output_dim)
#        q_s = torch.cat((q, n, p), dim=1)  
        
        # Step 5: Pass through Transformer encoder
#        out = model.transformer_encoder(q_s)

#        print(out.shape)

In [27]:
def getTEmbeds(dataframe, data, datasetModul, task_id, model):

    # get support set for cardiac disorders task
    item = datasetModul[task_id] 
    n_supp = item['n_supp']  
    p_supp = item['p_supp']  

    # simulate forward to get embeds
    model.eval()  # Set model to evaluation mode
    
    embeds = []
    with torch.no_grad():
        
        data = torch.from_numpy(data).float().to(device))
        
        # Step 1: Encode query, negative and positive supportset: 
        p = model.ln(model.encoder(p_supp))
        n = model.ln(model.encoder(n_supp))
        q = model.ln(model.encoder(data))

        # get params for label encoding
        device = p.device
        n_supps = p.shape[1]
        currentBatchSize = p.shape[0]
        
        # Step2: Encode labels of query,as well as negative and positive supportset
        pl = model.label_encoder( torch.ones(currentBatchSize, n_supps, dtype=torch.long).to(device) )
        nl = model.label_encoder (torch.zeros(currentBatchSize, n_supps, dtype=torch.long).to(device) )
        ql = model.label_encoder( torch.ones(currentBatchSize, dtype=torch.long).to(device) *2 )
            
        # Step 3: Concatenate input embeddings with label embeddings
        p = torch.cat((p, pl), dim=-1)
        n = torch.cat((n, nl), dim=-1)
        q = torch.cat((q, ql), dim=-1)

        # Step 4: Concatenate query with support
        q = q.unsqueeze(1)  # Add sequence dimension, Shape: (batch_size, 1, 2*output_dim)
        q_s = torch.cat((q, n, p), dim=1)  
        
        # Step 5: Pass through Transformer encoder
        out = model.transformer_encoder(q_s)

    return out.cpu().numpy()

SyntaxError: unmatched ')' (3942929763.py, line 14)

In [ ]:
#model.eval()  # Set model to evaluation mode
#with torch.no_grad():
#    encoded_embeds = model.encoder(torch.from_numpy(data).float().to(device)).cpu().numpy()

#task_name = "Cardiac disorders"
#plot_labels = dataset[task_name].values
#plot_tsne_embeddings(data, encoded_embeds, plot_labels, task_name,f'Trainingresult for the Cardiac disorders task with seed {seed}',seed,save=True)

# Notes

- ~~architectur ohne label encoding~~
- hp-search
- datensets checken
- maybe lr warm-up